### PR TITLE
Refactor to ANSI C

### PR DESCRIPTION
**Pull request by yqszxx**

### CODE REVIEW

**Comment by sequencer** [comment]
Wait for Chisel CI by @sinofp

**Comment by sequencer** [comment]
@yqszxx plz share your flow in the PR description page, that's very interesting.

**Comment by yqszxx** [comment]
This tool [cproto](https://sourceforge.net/projects/cproto/) is able to convert most of functions' prototype, but it isn't happy with modern standard library header files which causes functions with their arguments typed with types from std lib (like `FILE`) being ignored. Some manual dummy definitions placed in the ignored file fix this problem:
```c
typedef int FILE;
```
Then just use regex to stripe out `IN`, `register` and sort of stuffs.

**Review by sequencer — APPROVED** [review]
LGTM, merge if think this is done.

**Comment by sequencer** [comment]
@yqszxx plz rebase to master

**Comment by yqszxx** [comment]
Moved to #19.

**Pull request closed without merging**
